site_name: "Dynatrace Enablement Lab: Live Debugger Tutorial"
repo_name: "View Code on GitHub"
repo_url: "https://github.com/dynatrace-ace/enablement-live-debugger-bug-hunting"
nav:
  - '1. About': index.md
  - '2. Getting Started': getting-started.md
  - '3. Codespaces': codespaces.md
  - '4. Bug 1':
      - '4.1 Clear completed': 1-bug-clear-completed.md
      - '4.2 Hunt via Kubernetes App': 1-bug-hunt-via-k8s.md

  - '5. Bug 2':
      - '5.1 Special characters': 2-bug-special-characters.md
      - '5.2 Hunt via Distributed Traces': 2-bug-hunt-via-tracing.md

  - '6. Bug 3':
      - '6.1 Duplicate task': 3-bug-duplicate-task.md
      - '6.2 Hunt via Logs': 3-bug-hunt-via-logs.md

  - '7. Other settings':
      - '7.1 IDE Integration': ide-integration.md
      - '7.2 Mask sensitive data': mask-data.md
      - '7.3 Version control': version-control.md

  - '8. Cleanup': cleanup.md
  - '9. Resources': resources.md
  - "10. What's next?": whats-next.md

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - content.code.copy
    
  palette:
  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default 
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference

markdown_extensions:
  - toc:
      permalink: '#'
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: ["docs"]
  - attr_list
plugins:
    - search
